MAHA_CODE_MAPPING = {
    "10100": {"description": "License Plate Number", "category": "Vehicle Identification"},
    "10201": {"description": "Vehicle Manufacturer", "category": "Vehicle Identification"},
    "10200": {"description": "Vehicle Type", "category": "Vehicle Identification"},
    "10190": {"description": "Number of Axles", "category": "Vehicle Identification"},
    "10192": {"description": "Vehicle Chassis No.", "category": "Vehicle Identification"},
    "10107": {"description": "Inspection Date", "category": "Vehicle Identification"},
    "10131": {"description": "Inspection Time", "category": "Vehicle Identification"},
    "10512": {"description": "Inspector Name", "category": "Vehicle Identification"},
    "10010": {"description": "Lane Number", "category": "Vehicle Identification"},
    "30000": {"description": "Front Axle Side-Slip (m/km)", "category": "Side-Slip Test"},
    "30001": {"description": "Side-Slip Test Result", "category": "Side-Slip Test"},
    "31004": {"description": "Front Axle Shock Absorber Left (%)", "category": "Shock Absorber Test"},
    "31005": {"description": "Front Axle Shock Absorber Right (%)", "category": "Shock Absorber Test"},
    "31006": {"description": "Front Axle Shock Difference (%)", "category": "Shock Absorber Test"},
    "31020": {"description": "Rear Axle Shock Absorber Left (%)", "category": "Shock Absorber Test"},
    "31021": {"description": "Rear Axle Shock Absorber Right (%)", "category": "Shock Absorber Test"},
    "31022": {"description": "Rear Axle Shock Difference (%)", "category": "Shock Absorber Test"},
    "43110": {"description": "Vehicle Total Weight (kg)", "category": "Shock Absorber Test"},
    "50000": {"description": "Front Axle Brake Force Left (kN)", "category": "Brake Test"},
    "50001": {"description": "Front Axle Brake Force Right (kN)", "category": "Brake Test"},
    "50010": {"description": "Front Axle Brake Difference (%)", "category": "Brake Test"},
    "50100": {"description": "Rear Axle Brake Force Left (kN)", "category": "Brake Test"},
    "50101": {"description": "Rear Axle Brake Force Right (kN)", "category": "Brake Test"},
    "50110": {"description": "Rear Axle Brake Difference (%)", "category": "Brake Test"},
    "59000": {"description": "Parking Brake Force Left (kN)", "category": "Brake Test"},
    "59010": {"description": "Parking Brake Force Right (kN)", "category": "Brake Test"},
    "59020": {"description": "Parking Brake Difference (%)", "category": "Brake Test"},
    "59840": {"description": "Service Brake Efficiency (%)", "category": "Brake Performance"},
    "59880": {"description": "Parking Brake Efficiency (%)", "category": "Brake Performance"},
    "44024": {"description": "Tested Vehicle Weight (kg)", "category": "Brake Performance"},
    "70004": {"description": "Vehicle Identification Status", "category": "Visual Defects"},
    "70001": {"description": "Identification Defect Severity", "category": "Visual Defects"},
    "70024": {"description": "Exhaust Opacity Result", "category": "Emissions Test"},
    "70021": {"description": "Emission Defect Severity", "category": "Emissions Test"}
}
