#!/usr/bin/env bash
set -euo pipefail

# Install and enable the monitor_verification systemd timer/service.
# Usage:
#   sudo ./scripts/install_systemd_monitor.sh [--repo /path/to/repo] [--python /path/to/python] [--alert-to email] [--smtp-host host] [--smtp-port port]

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SERVICE_SRC="$REPO_DIR/scripts/systemd/monitor_verification.service"
TIMER_SRC="$REPO_DIR/scripts/systemd/monitor_verification.timer"
ENV_TEMPLATE="$REPO_DIR/scripts/monitor.env"

DEST_SERVICE=/etc/systemd/system/monitor_verification.service
DEST_TIMER=/etc/systemd/system/monitor_verification.timer
DEST_ENV=/etc/default/dump_listener_monitor

PYTHON_PATH="${1:-}" # optional override
ALERT_TO=""
SMTP_HOST=""
SMTP_PORT=""

usage(){
  cat <<EOF
Usage: sudo $0 [--repo REPO_DIR] [--python PYTHON] [--alert-to EMAIL] [--smtp-host HOST] [--smtp-port PORT]
Installs systemd unit and timer and enables the timer.
EOF
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO_DIR="$2"; SERVICE_SRC="$REPO_DIR/scripts/systemd/monitor_verification.service"; TIMER_SRC="$REPO_DIR/scripts/systemd/monitor_verification.timer"; ENV_TEMPLATE="$REPO_DIR/scripts/monitor.env"; shift 2;;
    --python) PYTHON_PATH="$2"; shift 2;;
    --alert-to) ALERT_TO="$2"; shift 2;;
    --smtp-host) SMTP_HOST="$2"; shift 2;;
    --smtp-port) SMTP_PORT="$2"; shift 2;;
    -h|--help) usage;;
    *) echo "Unknown arg: $1"; usage;;
  esac
done

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root (sudo)" >&2
  exit 2
fi

if [[ -z "$PYTHON_PATH" ]]; then
  # try repo venv
  if [[ -x "$REPO_DIR/.venv/bin/python" ]]; then
    PYTHON_PATH="$REPO_DIR/.venv/bin/python"
  else
    PYTHON_PATH="/usr/bin/python3"
  fi
fi

echo "Installing systemd service and timer from $REPO_DIR"

if [[ ! -f "$SERVICE_SRC" || ! -f "$TIMER_SRC" ]]; then
  echo "Service or timer source files not found in $REPO_DIR/scripts/systemd" >&2
  exit 3
fi

cp "$SERVICE_SRC" "$DEST_SERVICE"
cp "$TIMER_SRC" "$DEST_TIMER"
chmod 644 "$DEST_SERVICE" "$DEST_TIMER"

# Write environment file used by the service
echo "Writing $DEST_ENV"
cat > "$DEST_ENV" <<EOF
# Auto-generated by install_systemd_monitor.sh
PYTHONPATH=$PYTHON_PATH
ALERT_TO=${ALERT_TO}
ALERT_SMTP_HOST=${SMTP_HOST}
ALERT_SMTP_PORT=${SMTP_PORT}
EOF

systemctl daemon-reload
systemctl enable --now monitor_verification.timer

echo "monitor_verification.timer enabled and started"
systemctl status monitor_verification.timer --no-pager || true

echo "Installation complete. Edit $DEST_ENV to add credentials (SMTP or webhook) if needed."
